name: Deploy development

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v4
        with:
          name: pushkind-crawlers
          path: ./target/release/pushkind-crawlers
  deploy:
    needs: build-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: pushkind-crawlers
          path: ./target/release/
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CICD_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.CICD_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Deploy
        run: |
          ssh cicd@dantes.pushkind.com "supervisorctl stop crawlers"
          scp ./target/release/pushkind-crawlers cicd@dantes.pushkind.com:/var/www9/html/
          ssh cicd@dantes.pushkind.com "supervisorctl start crawlers"
